import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FaPlus, FaTrash, FaArrowUp, FaArrowDown, FaMagic, FaBolt } from "react-icons/fa";
import { resibotService, RESIBOT_EXPENSE_CATEGORIES, RESIBOT_EXPENSE_SOURCES } from "../../services/resibotService";
import {
  RB, ResibotHeader, Spinner, Card, Field, TextInput, TextArea, Select, PrimaryButton, EmptyState, } from "./resibotUi";
import { formatDisplayDate } from "../../../utils/dateFormat";

const money = (v) => `₹${Number(v || 0).toLocaleString("en-IN")}`;
const today = () => new Date().toISOString().slice(0, 10);
const empty = () => ({ category: "", amount: "", spentOn: today(), note: "" });

const INGEST_CHANNELS = [
  { key: "SMS", label: "Bank SMS", hint: "Paste a debit/spend SMS from your bank" },
  { key: "WHATSAPP", label: "WhatsApp invoice", hint: "Paste an invoice message you received" },
  { key: "EMAIL", label: "Email invoice", hint: "Paste an order/invoice email body" },
  { key: "OCR", label: "Invoice text", hint: "Paste text copied from an invoice / receipt" },
];

const ResibotExpenseScreen = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [summary, setSummary] = useState(null);
  const [expenses, setExpenses] = useState([]);
  const [form, setForm] = useState(empty());
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);

  // Auto-capture (Expense Automation ingestion)
  const [showAuto, setShowAuto] = useState(false);
  const [channel, setChannel] = useState("SMS");
  const [rawText, setRawText] = useState("");
  const [ingesting, setIngesting] = useState(false);
  const [ingestMsg, setIngestMsg] = useState(null);

  const load = async () => {
    const [s, list] = await Promise.all([
      resibotService.getExpenseSummary(),
      resibotService.listExpenses(new Date().getMonth() + 1, new Date().getFullYear()),
    ]);
    setSummary(s?.success ? s.data : null);
    setExpenses(list?.success && Array.isArray(list.data) ? list.data : []);
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));

  const save = async () => {
    if (!form.category || form.amount === "") return;
    setSaving(true);
    await resibotService.addExpense({
      category: form.category, amount: Number(form.amount),
      spentOn: form.spentOn || today(), note: form.note || null, source: "Manual", sourceType: "MANUAL",
    });
    setForm(empty()); setShowForm(false); setSaving(false);
    await load();
  };

  const runIngest = async () => {
    if (!rawText.trim()) return;
    setIngesting(true); setIngestMsg(null);
    const res = await resibotService.ingestExpense({ channel, rawText: rawText.trim() });
    setIngesting(false);
    if (res?.success) {
      const d = res.data || {};
      if (d.status === "EXPENSED") {
        setIngestMsg({ ok: true, text: `Booked ${money(d.amount)} • ${d.category}${d.merchant ? ` • ${d.merchant}` : ""}${d.warrantyMonths ? " • warranty reminder created" : ""}` });
        setRawText("");
        await load();
      } else if (d.status === "PARSED") {
        setIngestMsg({ ok: true, text: `Parsed ${d.amount ? money(d.amount) : ""} ${d.category || ""} — low confidence, review under "Captured" if needed.` });
        setRawText("");
        await load();
      } else if (d.status === "FAILED") {
        setIngestMsg({ ok: false, text: d.errorMessage || "Couldn't detect an amount. Try the manual form." });
      } else {
        setIngestMsg({ ok: true, text: "Received." });
      }
    } else {
      setIngestMsg({ ok: false, text: res?.message || "Ingestion failed." });
    }
  };

  const remove = async (id) => { if (!window.confirm("Delete this expense?")) return; await resibotService.deleteExpense(id); await load(); };

  if (loading) return <Spinner />;

  const delta = Number(summary?.monthOnMonthDelta || 0);
  const top = summary?.topCategories || [];
  const maxTop = top.reduce((m, t) => Math.max(m, Number(t.amount || 0)), 0) || 1;
  const autoCount = expenses.filter((e) => e.autoGenerated || (e.sourceType && e.sourceType !== "MANUAL")).length;

  return (
    <div className="rb-page">
      <ResibotHeader
        title="Expense Snapshot" subtitle="Auto-tracked monthly spend"
        onBack={() => navigate("/customer/app/resibot")}
        right={<button type="button" onClick={() => setShowForm((s) => !s)} style={{ width: 38, height: 38, borderRadius: 12, border: "none", background: RB.brand, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}><FaPlus size={14} /></button>}
      />

      {/* Summary */}
      <Card style={{ marginBottom: 14, display: "flex", gap: 18, alignItems: "center" }}>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 24, fontWeight: 800 }}>{money(summary?.currentMonthTotal)}</div>
          <div style={{ fontSize: 12, color: RB.muted }}>This month{autoCount > 0 ? ` · ${autoCount} auto-tracked` : ""}</div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: delta > 0 ? "#DC2626" : "#16A34A", display: "inline-flex", alignItems: "center", gap: 4 }}>
            {delta > 0 ? <FaArrowUp size={11} /> : <FaArrowDown size={11} />} {money(Math.abs(delta))}
          </div>
          <div style={{ fontSize: 11.5, color: RB.muted }}>vs last month {money(summary?.lastMonthTotal)}</div>
        </div>
      </Card>

      {/* Auto-capture entry point */}
      <Card style={{ marginBottom: 14 }}>
        <button type="button" onClick={() => setShowAuto((s) => !s)}
          style={{ width: "100%", border: "none", background: "transparent", cursor: "pointer", display: "flex", alignItems: "center", gap: 10, padding: 0, color: "inherit", textAlign: "left" }}>
          <span style={{ width: 34, height: 34, borderRadius: 10, background: RB.brand, color: "#fff", display: "grid", placeItems: "center", flexShrink: 0 }}><FaMagic size={14} /></span>
          <span style={{ flex: 1 }}>
            <span style={{ display: "block", fontSize: 14, fontWeight: 700 }}>Auto-capture an expense</span>
            <span style={{ display: "block", fontSize: 11.5, color: RB.muted }}>Paste a bank SMS or invoice — we read the amount, merchant & GST</span>
          </span>
        </button>

        {showAuto && (
          <div style={{ marginTop: 14 }}>
            <Field label="Source">
              <Select value={channel} onChange={(e) => setChannel(e.target.value)}>
                {INGEST_CHANNELS.map((c) => <option key={c.key} value={c.key}>{c.label}</option>)}
              </Select>
            </Field>
            <Field label={INGEST_CHANNELS.find((c) => c.key === channel)?.hint || "Paste text"}>
              <TextArea value={rawText} onChange={(e) => setRawText(e.target.value)} rows={4}
                placeholder={'e.g. "Rs.2,845.00 debited at Amazon on 12/06/2026. GST Rs 433. Warranty 12 months."'} />
            </Field>
            <PrimaryButton onClick={runIngest} disabled={ingesting || !rawText.trim()}>
              {ingesting ? "Reading…" : "Capture expense"}
            </PrimaryButton>
            {ingestMsg && (
              <div style={{ marginTop: 10, fontSize: 12.5, padding: "8px 10px", borderRadius: 10, background: ingestMsg.ok ? "rgba(22,163,74,.1)" : "rgba(220,38,38,.1)", color: ingestMsg.ok ? "#16A34A" : "#DC2626" }}>
                {ingestMsg.text}
              </div>
            )}
          </div>
        )}
      </Card>

      {/* Top categories */}
      {top.length > 0 && (
        <Card style={{ marginBottom: 18 }}>
          <div style={{ fontSize: 13.5, fontWeight: 700, marginBottom: 10 }}>Top categories</div>
          <div style={{ display: "grid", gap: 9 }}>
            {top.map((t) => (
              <div key={t.category}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12.5, marginBottom: 3 }}>
                  <span>{t.category}</span><span style={{ fontWeight: 700 }}>{money(t.amount)}</span>
                </div>
                <div style={{ height: 6, borderRadius: 999, background: RB.border }}>
                  <div style={{ height: "100%", borderRadius: 999, background: RB.brand, width: `${(Number(t.amount) / maxTop) * 100}%` }} />
                </div>
              </div>
            ))}
          </div>
        </Card>
      )}

      {showForm && (
        <Card style={{ marginBottom: 18 }}>
          <Field label="Category">
            <Select value={form.category} onChange={set("category")}>
              <option value="">Select category</option>
              {RESIBOT_EXPENSE_CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
            </Select>
          </Field>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
            <Field label="Amount (₹)"><TextInput type="number" value={form.amount} onChange={set("amount")} /></Field>
            <Field label="Date"><TextInput type="date" value={form.spentOn} onChange={set("spentOn")} /></Field>
          </div>
          <Field label="Note (optional)"><TextInput value={form.note} onChange={set("note")} placeholder="What was it for?" /></Field>
          <PrimaryButton onClick={save} disabled={saving}>{saving ? "Saving…" : "Add expense"}</PrimaryButton>
        </Card>
      )}

      <h3 style={{ fontSize: 16, margin: "0 0 10px", fontWeight: 700 }}>This month's entries</h3>
      {expenses.length === 0 ? (
        <EmptyState>No expenses logged this month. Pay a bill or paste an SMS to auto-track one.</EmptyState>
      ) : (
        <div style={{ display: "grid", gap: 8 }}>
          {expenses.map((e) => {
            const auto = e.autoGenerated || (e.sourceType && e.sourceType !== "MANUAL");
            const sourceLabel = RESIBOT_EXPENSE_SOURCES[e.sourceType] || e.source;
            return (
              <Card key={e.id} style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, display: "flex", alignItems: "center", gap: 6 }}>
                    {e.category}
                    {auto && (
                      <span title="Auto-tracked" style={{ display: "inline-flex", alignItems: "center", gap: 3, fontSize: 10, fontWeight: 700, color: RB.brand, background: "rgba(225,29,72,.1)", padding: "1px 7px", borderRadius: 999 }}>
                        <FaBolt size={8} /> AUTO
                      </span>
                    )}
                  </div>
                  <div style={{ fontSize: 12, color: RB.muted, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {formatDisplayDate(e.spentOn, "—")}
                    {e.merchant ? ` · ${e.merchant}` : (sourceLabel ? ` · ${sourceLabel}` : "")}
                    {e.note && !e.merchant ? ` · ${e.note}` : ""}
                  </div>
                </div>
                <strong style={{ fontSize: 14.5 }}>{money(e.amount)}</strong>
                <button type="button" onClick={() => remove(e.id)} aria-label="Delete"
                  style={{ width: 32, height: 32, borderRadius: 8, border: "1px solid #DC2626", background: "transparent", color: "#DC2626", display: "grid", placeItems: "center", cursor: "pointer" }}>
                  <FaTrash size={11} />
                </button>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default ResibotExpenseScreen;
