/**
 * Stamp a fresh build id into the app on every build/start.
 *
 * Runs via the `prebuild` / `prestart` npm lifecycle hooks (so it fires
 * automatically before `react-scripts build` and `react-scripts start`).
 *
 * It writes the SAME id to two places:
 *   1. public/version.json   -> served and fetched at runtime (no-cache)
 *   2. src/generated/buildId.js -> compiled into the JS bundle (BUILD_ID)
 *   3. public/sw.js CACHE_VERSION -> forces a fresh service-worker cache
 *
 * The app (OtaUpdateGate) compares the served buildId to its compiled BUILD_ID;
 * if they differ, a new build is live -> show the "new version" bar. After the
 * user reloads, the fresh bundle's BUILD_ID matches version.json -> no bar.
 *
 * The human-facing `version` / `notes` in version.json are preserved as-is.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const buildId = String(Date.now());
const buildTime = new Date().toISOString();

// 1) public/version.json — keep version/notes, refresh buildId + buildTime.
const versionPath = path.join(root, "public", "version.json");
let vj = {};
try {
  vj = JSON.parse(fs.readFileSync(versionPath, "utf8"));
} catch {
  vj = {};
}
vj.version = vj.version || "1.0.0";
vj.buildId = buildId;
vj.buildTime = buildTime;
fs.writeFileSync(versionPath, JSON.stringify(vj, null, 2) + "\n");

// 2) src/generated/buildId.js — compiled into the bundle.
const genDir = path.join(root, "src", "generated");
fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(
  path.join(genDir, "buildId.js"),
  `// AUTO-GENERATED by scripts/stamp-version.js — do not edit.\n` +
    `export const BUILD_ID = ${JSON.stringify(buildId)};\n` +
    `export const BUILD_TIME = ${JSON.stringify(buildTime)};\n`
);

// 3) public/sw.js — make every build use a new cache namespace.
const swPath = path.join(root, "public", "sw.js");
try {
  const swSource = fs.readFileSync(swPath, "utf8");
  const nextSwSource = swSource.replace(
    /const CACHE_VERSION = ["'`][^"'`]+["'`];/,
    `const CACHE_VERSION = ${JSON.stringify(`v${buildId}`)};`
  );
  if (nextSwSource !== swSource) {
    fs.writeFileSync(swPath, nextSwSource);
  }
} catch (err) {
  console.warn(`[stamp-version] skipped service-worker stamp: ${err.message}`);
}

console.log(`[stamp-version] buildId=${buildId} (${buildTime})`);
